### ISSUE TITLE
MaintenanceTracker does not stop tracking after building is removed.

### ISSUE THREAD

**Issue by FluffierThanThou** [FluffierThanThou/Fluffy_Breakdowns#6]
Hello, so i had some bug for the first time with fluffy breakdowns, i had an hydroponics basin that nobody came to maintain, and when it eventually broke down they could not repair it, so i deconstructed it but still i had that "white smoke" coming from where the basin use to be afterward, when i restarted my game the white smoke was gone, weird bug because this happend to only a single basin, not the other ones around it, not sure what is causing this.

**Comment by KnightRaven0** [comment]
I am having a similar problem, except that it happened for all my machines and restarting doesn't help. Nor does destroying all maintenance requiring objects.

**Comment by FluffierThanThou** [comment]
@KnightRaven0 save game and output_log.txt please!

**Comment by KnightRaven0** [comment]
Well, I am sad that I didn't check sooner. I went into the source and made it so that the smoke just doesn't show up, which did give me a handy if not a bit intrusive text output of all the maintain percentages, but after playing for a bit, then now replacing the assembly to stock, I do not have the white smoke anymore. If it shows up again I will post the log. One odd thing was the smoke was very positioned very far away from any machines in some situations.

**Comment by FluffierThanThou** [comment]
For the record, that % text is debug output, if you compile the mod with release target it won't show up.
